### ISSUE TITLE
how upgrade to last version

### ISSUE THREAD

**Issue by X0R1972** [Arno0x/DBC2#2]
how can i upgrade i have version 0.2..4 and see that there is  new version 0.2.6 available

do i have to create every time a new publishStage for a new agent or i can use the same.
and the last question ..the victim do they have also  dropbox installed on pc.?

**Comment by Bry-fi** [comment]
I can answer your second question confidently. The victims does not have to have dropbox downloaded as it only uses their servers for communications (HTTP GET/POST). And to update to new version try:

root@you:/pentest/DropboxC2/ git pull

**Comment by Arno0x** [comment]
As per the upgrade, yes you can use `git pull` or you can download the latest package as a ZIP from Github and extract it. Either way you'll probably want to save your current `config.py` file as it may contain your access token and master key (if you saved them into this config file).

Regarding your other question: once a stage is published on dropbox (_associated with a given dropbox access token_), you don't have to publish it again. Every time you launch the controller (_dropboxc2.py_) it will get the list of all published stages and modules so that you can use them and work with them.

Finally, as @Bry-fi said, the victim doesn't have to have dropbox installed on their PC, this is totally independent. DBC2 agent is self sufficient.
