### ISSUE TITLE
Error communicating with the Dropbox server

### ISSUE THREAD

**Issue by X0R1972** [Arno0x/DBC2#3]
first this tool work good now i have this error 

HTTPSConnectionPool(host='api.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/list_folder (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb706de8c>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

any idee how to fix this..and i want also to say to you ,you did a very good jobcreating this tool, this is really a good tool !!

**Comment by Arno0x** [comment]
It looks like the DBC2 controller doesn't have network connectivity. Are you able to `ping api.dropboxapi.com` ?
Or maybe are you behind an http proxy ?

**Comment by X0R1972** [comment]
thanks for reply
it's strange today everything work normal..
i close this issue now and if this error happends again i contact you

**Comment by Arno0x** [comment]
While it is perfectly fine to open issues, it is important to ensure that the issue is really related to the software (DBC2 in this case) and not some network connectivity issue (as it seems to be the case in the above-mentioned error message), especially since network connectivity issues are easy to pinpoint.
Cheers
